---
author: Prof. Dr. Pedro Rafael D. Marinho
return-address: 
  - Department of Statistics
  - Federal University of Paraíba
  - João Pessoa, Paraíba - PB, Brazil
return-email: pedro.rafael.marinho@gmail.com
papersize: letter
yourmail: pedro.rafael.marinho@gmail.com
return-url: https://prdm0.rbind.io/
urlcolor: blue
linkcolor: red
address:
  - "**Replies to reviewers**"
  - "**REVSTAT**"
  - ""
subject: "Marshall and Olkin-G and Gamma-G family of distribution: properties and applications"
opening: | 
  | Dear **REVSTAT** Executive Editor and Reviews,
closing: Kind regards,
signature: |
  | Prof. Dr. Pedro Rafael D. Marinho
  | (DSc in Statistics from Federal University of Pernambuco)
output: 
  komaletter::komaletter:
    keep_tex: true
---

in this letter, I will respond to each of the reviewers valuable contributions. We try to accept all suggestions, aiming at a significant improvement of our article. After each questioning, the respective answers will be given. As suggested by the second reviewer, the title of the paper was modified and better represents the proposal of the work.

**REVIEW I**:

1 – The equality $h(x)=f(x)/(1-F(x))$ is a well known relation between hazard, density and
survival functions. It is not a definition of density or risk functions. Therefore, in page 3,
line 12, the part of the sentence "defined by $h(x)=f(x)/(1-F(x))$" should be omitted.

*Response*:

2 – The expression (3.1) in page 6 corresponds to the log-likelihood of a MO-$\Gamma$-$G$
distribution, considering a Weibull distribution for $G$ (although there is an error in the
last sum of line 1), not a general distribution with a $\eta$ vector of parameters. Therefore,
the text or the expression should be written accordingly.

*Response*:


3 – It is not clear why it is considered the Weibull distribution (for $G$) in Figure 1,
eventually in expression (3.1) and in the applications, whereas for the simulations it is
chosen the Dagum distribution. These choices should be clarified.

*Response*: \textcolor{red}{Indeed, the way in which the application section was written suggests that an attempt was made to fix the $G\sim Weibull$ distribution as one of the necessary assumptions for the analysis. What actually happened is that for the datasets used, the Weibull distribution appeared to be a suitable distribution.}

\textcolor{red}{In order to remove some ambiguity, we opted to extend the simulation studies, where we also include the simulations, considering $G\sim Weibull$.
Indeed, the way in which the application section was written suggests that an attempt was made to fix the $G\sim Weibull$ distribution as one of the necessary assumptions for the analysis. What actually happened is that for the datasets used, the Weibull distribution appeared to be a suitable distribution.}

\textcolor{red}{In order to remove some ambiguity, we opted to extend the simulation studies, where we also include the simulations, considering $G\sim Weibull$.}

4 – As the Dagum distribution is used in the simulations, the generated PDF should also
be in Table 1.

*Response*: \textcolor{red}{Thanks for the observation. The Dagum distribution was included in Table 1.}

5 – As the `goodness.fit` function gives several statistics, the authors should justify why
they only chose the Anderson Darling and Cramer-von Mises statistics.

*Response*: \textcolor{red}{The use of the $A^*$ and $W^*$ statistics, Anderson-Darling and Cramer-von Mises statistics, respectively, corrected by Chen and Balakrishnan, in the paper entitled "A General Purpose Approximate Goodness-of-Fit Test" (see [link](https://www.tandfonline.com/doi/abs/10.1080/00224065.1995.11979578)) are suitable for comparing models that are not necessarily embedded. Therefore, considering the statistics returned by the `goodness.fit` function and considering the distributions compared, we understand that the statistics $A^*$ and $W^*$ are the most suitable for making the comparisons.}

\textcolor{red}{The **AdequacyModel** package was developed by one of the authors of this paper and was published at [https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0221487](https://journals .plos.org/plosone/article?id=10.1371/journal.pone.0221487). A code inspection of the `goodness.fit` function can be done by looking at the [link](https://github.com/prdm0/AdequacyModel/blob/master/R/goodness.fit.R) on GitHub, where it is hosted the development versioning of the package.}

*Minor points:*

1 – page 1, line 8 of Section 1, correct for "vector".

*Response*:

2 – page 2: confirm the expressions of $Q_{MO-G}(u)$ (line 9) and $W$ (line22).

*Response*:

3 – page 2, line -4 of Section 1, correct for "are".

*Response*:

4 – page 3, line 4, where it is written "gamma density unit scale and shape $a>0$," I suggest replacing it by "gamma density with unit scale parameter and shape parameter $a>0$,".

*Response*:

5 – page 3, $3^{rd}$ paragraph, replace "Table 2" by "Table 1".

*Response*:

6 – page 3, line-8, correct for "(0,1)".

*Response*:

7 – Figure 1: I suggest to change the lines to different types (even letting the colours as
they are) so as to enable the interpretation in a black and white print. Also, the letters
assigned to the parameters must agree with those in Table 1 (and, eventually, with those
in expression (3.1)).

*Response*: \textcolor{red}{Thanks a lot for the suggestion. All changes have been made. In fact, in a black and white print, solid lines will not help to differentiate the graphics.}

8 – page 3, lines-8,-7, where it is written "of the baseline $Q_F$ $Q_G(.)$." I suggest replacing
it by "of the $Q_F$ of the baseline distribution $G$, $Q_G(.).$".

*Response*:

9 – page 3, line-6, correct for "(1.1) and".

*Response*:

10 – page 7: the label of the table should be on the top, like the rest of the tables.

*Response*:

11 – page 11, line 4, correct for "distribution".

*Response*:

12 – In expressions (6.4) and (6.6), try to improve the output as the reference numbers
are to close to the formulas.

*Response*:

13 – I suggest to make the labels of Figure 1 and of tables in \LaTeX, not in R.

*Response*: \textcolor{red}{Thanks for the sugestion. The change suggestion has been implemented.}

14 – The references “R Core Team. …” and “Rizzo, …” are in the wrong order.

*Response*:


**REVIEW II**:

1 - The article is written in an overly summarized form and is sometimes unattractive to the
reader of any journal. That alone could lead to your rejection. In addition, I do suggest
reviewing the use of English carefully, and considerable rewording and pruning to make
the paper more concise and precise.

*Response*:

2 - When I see a new paper about a new distribution, I wonder if it is due to any interesting
properties or it arises naturally in some observable process like natural phenomena. I
would like to see these arguments defended more clearly in the article by the authors.
Could you do that?

*Response*:

3 - The bibliography does not have many recent publications such as Martinez-Florez et al.
(2020) and Magalhaes et al. (2020). I also suggest authors to create the state-of-art related
to this topic in the first section that definitively needs to be improved.

*Response*:

4 - I expect to see more detailed discussion in the simulation study and real data analysis.
Could you revise these sections, including the conclusion section that is actually weak?

5 - Suggestions: (i) Rewrite the paper title since the current one is nothing enlightening. How
about naming the proposed distribution?. (ii) Place section 6 (properties) before section 4
(simulation). (iii) Reorganize the presentation of the tables. (iv) Put the simulation code
in Supplementary material.

*Response*:

- (i) \textcolor{red}{Really, the title of the paper was really bad. We switched to **Marshall and Olkin-G and Gamma-G family of distribution: properties and applications**. We believe that the title now clarifies the paper's proposal better.}
- (ii) \textcolor{red}{Change made. Thanks for the sugestion.}
- (iii) \textcolor{red}{Thanks for the observation. The presentation of tables has been reorganized.}
- (iv) \textcolor{red}{Thanks for the sugestion.We chose to put the code for the simulations in a repository on GitHub. Thus, we considerably reduced the number of pages in the article and made it easier for readers of the material to reuse the code. With the code on GitHub it is also possible to verify the implementation and validate the simulations obtained. To access the codes, see the} [link](https://github.com/prdm0/MOGG/tree/master/code/simulations).