---
author: Prof. Dr. Pedro Rafael D. Marinho
return-address: 
  - Department of Statistics
  - Federal University of Paraíba
  - João Pessoa, Paraíba - PB, Brazil
return-email: pedro.rafael.marinho@gmail.com
papersize: letter
yourmail: pedro.rafael.marinho@gmail.com
return-url: https://prdm0.rbind.io/
urlcolor: blue
linkcolor: red
address:
  - "**Executive Editor**"
  - "**REVSTAT**"
  - ""
subject: "A new family of distributions: properties and applications"
opening: | 
  | Dear **REVSTAT** Executive Editor,
closing: Kind regards,
signature: |
  | Prof. Dr. Pedro Rafael D. Marinho
  | (DSc in Statistics from Federal University of Pernambuco)
output: 
  komaletter::komaletter:
    keep_tex: true
---

we would like to present the paper entitled **A new family of distributions: properties and applications** to the REVSTAT. This article introduces a new family by combining the Marshall and Olkin-G and Gamma-G classes. The family has only two extra shape parameters and can be a better model than other existing classes of distributions. Simulations
are performed to verify the consistency of the estimators. Its flexibility is shown using two real data sets.

This article submitted to this journal is co-authored by researchers Gauss M.  Cordeiro (PhD in Statistics from Imperial College, 1982) of the Statistics Department of Federal University of Pernambuco and Dra. Maria do Carmo S. Lima Federal of the Statistics Department of Federal University of Pernambuco.

This material has not been submitted to any other Journal.